site_name: Osixia / Open Source
site_description: Osixia Open Source Projects Documentation
site_author: Bertrand Gouny
site_url: https://opensource.osixia.net

copyright: Osixia - Where healthy systems and happy people thrive 🌴

repo_name: osixia/opensource
repo_url: https://github.com/osixia/opensource

edit_uri: edit/main/docs/

nav:
  - Home:
    - index.md
  - Projects: 
    - projects/index.md
    - Container Images:
        - projects/container-images/index.md
        - osixia/baseimage:
          - projects/container-images/baseimage/index.md
          - projects/container-images/baseimage/quickstart.md
          - projects/container-images/baseimage/how-it-works.md
          - projects/container-images/baseimage/advanced-runtime-guide.md
          - projects/container-images/baseimage/production-and-integration.md
          - projects/container-images/baseimage/positioning-and-trade-offs.md
          - '🤖 Container Command':
            - projects/container-images/baseimage/container-command/index.md
            - Main Commands:
              - projects/container-images/baseimage/container-command/install.md
              - projects/container-images/baseimage/container-command/generate.md
              - projects/container-images/baseimage/container-command/run.md
            - Runtime Commands:
              - projects/container-images/baseimage/container-command/runtime/packages.md
              - projects/container-images/baseimage/container-command/runtime/processes.md
              - projects/container-images/baseimage/container-command/runtime/services.md
            - Environment Commands:
              - projects/container-images/baseimage/container-command/environment/environment.md
              - projects/container-images/baseimage/container-command/environment/envsubst.md
            - projects/container-images/baseimage/container-command/filesystem.md
            - Log Command:
              - projects/container-images/baseimage/container-command/log/index.md
              - projects/container-images/baseimage/container-command/log/fatal.md
              - projects/container-images/baseimage/container-command/log/error.md
              - projects/container-images/baseimage/container-command/log/warning.md
              - projects/container-images/baseimage/container-command/log/info.md
              - projects/container-images/baseimage/container-command/log/debug.md
              - projects/container-images/baseimage/container-command/log/trace.md
              - projects/container-images/baseimage/container-command/log/level.md
          - '🎮 Tutorials':
            - projects/container-images/baseimage/tutorials/index.md
            - projects/container-images/baseimage/tutorials/nginx.md
            - projects/container-images/baseimage/tutorials/nginx-php-fpm.md
        - osixia/keepalived:
          - projects/container-images/keepalived/index.md
          - projects/container-images/keepalived/quickstart.md
          - projects/container-images/keepalived/environment-variables.md
        - osixia/openldap:
          - projects/container-images/openldap/index.md
  - contribute.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - toc.integrate
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  logo: assets/images/osixia-logo.png
  favicon: assets/images/osixia-logo.png

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange

extra:
  homepage: https://opensource.osixia.net
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/osixia
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/osixia
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/osixia

extra_css:
  - assets/stylesheets/main.css
